-- Insert dummy records for clients
INSERT INTO clients (name, lastname, email, age) VALUES
('John', 'Doe', 'john.doe@example.com', 30),
('Jane', 'Smith', 'jane.smith@example.com', 25),
('Michael', 'Johnson', 'michael.johnson@example.com', 40),
('Emily', 'Williams', 'emily.williams@example.com', 35),
('Christopher', 'Brown', 'christopher.brown@example.com', 28),
('Amanda', 'Jones', 'amanda.jones@example.com', 32),
('David', 'Martinez', 'david.martinez@example.com', 45),
('Sarah', 'Garcia', 'sarah.garcia@example.com', 27),
('Robert', 'Rodriguez', 'robert.rodriguez@example.com', 38),
('Jennifer', 'Lopez', 'jennifer.lopez@example.com', 31),
('James', 'Lee', 'james.lee@example.com', 29),
('Jessica', 'Hernandez', 'jessica.hernandez@example.com', 33),
('Daniel', 'Gonzalez', 'daniel.gonzalez@example.com', 36),
('Michelle', 'Perez', 'michelle.perez@example.com', 26),
('William', 'Wilson', 'william.wilson@example.com', 42),
('Ashley', 'Taylor', 'ashley.taylor@example.com', 34),
('Matthew', 'Anderson', 'matthew.anderson@example.com', 39),
('Taylor', 'Thomas', 'taylor.thomas@example.com', 37),
('Lauren', 'Moore', 'lauren.moore@example.com', 24),
('Andrew', 'Jackson', 'andrew.jackson@example.com', 41);

-- Insert dummy records for products
INSERT INTO products (name, description, price) VALUES
('Laptop', '15.6" Intel Core i5 8GB RAM 256GB SSD', 799.99),
('Smartphone', '6.4" AMOLED Display 128GB Storage', 599.99),
('Headphones', 'Wireless Noise-Canceling Headphones', 199.99),
('Tablet', '10.1" Android Tablet 64GB Storage', 299.99),
('Smartwatch', 'Fitness Tracker with Heart Rate Monitor', 149.99),
('Camera', 'Mirrorless Camera with 24MP Sensor', 899.99),
('Speaker', 'Bluetooth Portable Speaker with 360-degree Sound', 129.99),
('Gaming Console', '4K Gaming Console with 1TB Storage', 499.99),
('Printer', 'All-in-One Wireless Printer', 249.99),
('Router', 'Dual-Band Wi-Fi 6 Router', 179.99),
('External Hard Drive', '1TB USB 3.0 Portable External Hard Drive', 79.99),
('Monitor', '27" IPS LED Monitor with Full HD Resolution', 229.99),
('Keyboard', 'Mechanical Gaming Keyboard with RGB Lighting', 99.99),
('Mouse', 'Wireless Optical Mouse', 49.99),
('Backpack', 'Laptop Backpack with USB Charging Port', 39.99),
('Desk', 'Adjustable Standing Desk', 299.99),
('Chair', 'Ergonomic Office Chair with Lumbar Support', 199.99),
('Smart Bulbs', 'Smart LED Light Bulbs (Pack of 4)', 59.99),
('Security Camera', 'Indoor/Outdoor HD Security Camera', 129.99),
('Thermostat', 'Smart Thermostat with Wi-Fi Connectivity', 149.99);
